package ai

import "testing"

// Golden values generated by running the TS shortHash (cyrb53 variant from
// packages/ai/src/utils/hash.ts) under Node — the Go port must be
// hash-compatible so cache keys and shortened ids match across both ports.
func TestShortHashParityWithTS(t *testing.T) {
	cases := map[string]string{
		"":            "k4n83c7h0j2b",
		"a":           "m8735310ae7sx",
		"hello world": "n7rb4n1m39uz8",
		"The quick brown fox jumps over the lazy dog": "eig47k1th3xf1",
		"tool_call_id_1234567890":                     "1i534er1ty98so",
		"🙈 emoji ünïcode ☃":                           "iuow8j6wl60r",
		"claude-opus-4-8":                             "3ufvqzacnbe7",
	}
	for input, want := range cases {
		if got := ShortHash(input); got != want {
			t.Errorf("ShortHash(%q) = %q, want %q", input, got, want)
		}
	}
}
